spring.application.name=Ponto

# Chave secreta (Obrigatório)
jwt.secret-key=minha_chave_secreta_super_longa_e_segura_32_chars

# Tempo de expiração (Opcional - Padrão 24h)
jwt.expiration-time=43200000 

# Rotas públicas que NÃO precisam de token (Opcional mas muito recomendado)
jwt.excluded-paths=/auth/login, /public/**, /swagger-ui/**